// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/shelves_proto/shelves.proto

package shelvesgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shelf int32

const (
	Shelf_SHELF_UNSPECIFIED Shelf = 0
	Shelf_SHELF_TO_READ     Shelf = 1
	Shelf_SHELF_READING     Shelf = 2
	Shelf_SHELF_FINISHED    Shelf = 3
)

// Enum value maps for Shelf.
var (
	Shelf_name = map[int32]string{
		0: "SHELF_UNSPECIFIED",
		1: "SHELF_TO_READ",
		2: "SHELF_READING",
		3: "SHELF_FINISHED",
	}
	Shelf_value = map[string]int32{
		"SHELF_UNSPECIFIED": 0,
		"SHELF_TO_READ":     1,
		"SHELF_READING":     2,
		"SHELF_FINISHED":    3,
	}
)

func (x Shelf) Enum() *Shelf {
	p := new(Shelf)
	*p = x
	return p
}

func (x Shelf) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Shelf) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_shelves_proto_shelves_proto_enumTypes[0].Descriptor()
}

func (Shelf) Type() protoreflect.EnumType {
	return &file_proto_shelves_proto_shelves_proto_enumTypes[0]
}

func (x Shelf) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Shelf.Descriptor instead.
func (Shelf) EnumDescriptor() ([]byte, []int) {
	return file_proto_shelves_proto_shelves_proto_rawDescGZIP(), []int{0}
}

type ShelfItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Shelf         Shelf                  `protobuf:"varint,3,opt,name=shelf,proto3,enum=shelves.v1.Shelf" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShelfItem) Reset() {
	*x = ShelfItem{}
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShelfItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShelfItem) ProtoMessage() {}

func (x *ShelfItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShelfItem.ProtoReflect.Descriptor instead.
func (*ShelfItem) Descriptor() ([]byte, []int) {
	return file_proto_shelves_proto_shelves_proto_rawDescGZIP(), []int{0}
}

func (x *ShelfItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShelfItem) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *ShelfItem) GetShelf() Shelf {
	if x != nil {
		return x.Shelf
	}
	return Shelf_SHELF_UNSPECIFIED
}

type GetShelfItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfItemRequest) Reset() {
	*x = GetShelfItemRequest{}
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfItemRequest) ProtoMessage() {}

func (x *GetShelfItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfItemRequest.ProtoReflect.Descriptor instead.
func (*GetShelfItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_shelves_proto_shelves_proto_rawDescGZIP(), []int{1}
}

func (x *GetShelfItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetShelfItemRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetShelfItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ShelfItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfItemResponse) Reset() {
	*x = GetShelfItemResponse{}
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfItemResponse) ProtoMessage() {}

func (x *GetShelfItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfItemResponse.ProtoReflect.Descriptor instead.
func (*GetShelfItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_shelves_proto_shelves_proto_rawDescGZIP(), []int{2}
}

func (x *GetShelfItemResponse) GetItem() *ShelfItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateShelfItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ShelfItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfItemRequest) Reset() {
	*x = CreateShelfItemRequest{}
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfItemRequest) ProtoMessage() {}

func (x *CreateShelfItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfItemRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_shelves_proto_shelves_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShelfItemRequest) GetItem() *ShelfItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateShelfItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ShelfItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfItemResponse) Reset() {
	*x = CreateShelfItemResponse{}
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfItemResponse) ProtoMessage() {}

func (x *CreateShelfItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shelves_proto_shelves_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfItemResponse.ProtoReflect.Descriptor instead.
func (*CreateShelfItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_shelves_proto_shelves_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShelfItemResponse) GetItem() *ShelfItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_proto_shelves_proto_shelves_proto protoreflect.FileDescriptor

const file_proto_shelves_proto_shelves_proto_rawDesc = "" +
	"\n" +
	"!proto/shelves_proto/shelves.proto\x12\n" +
	"shelves.v1\"f\n" +
	"\tShelfItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12'\n" +
	"\x05shelf\x18\x03 \x01(\x0e2\x11.shelves.v1.ShelfR\x05shelf\"G\n" +
	"\x13GetShelfItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"A\n" +
	"\x14GetShelfItemResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.shelves.v1.ShelfItemR\x04item\"C\n" +
	"\x16CreateShelfItemRequest\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.shelves.v1.ShelfItemR\x04item\"D\n" +
	"\x17CreateShelfItemResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.shelves.v1.ShelfItemR\x04item*X\n" +
	"\x05Shelf\x12\x15\n" +
	"\x11SHELF_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSHELF_TO_READ\x10\x01\x12\x11\n" +
	"\rSHELF_READING\x10\x02\x12\x12\n" +
	"\x0eSHELF_FINISHED\x10\x032\xbf\x01\n" +
	"\x0eShelvesService\x12Q\n" +
	"\fGetShelfItem\x12\x1f.shelves.v1.GetShelfItemRequest\x1a .shelves.v1.GetShelfItemResponse\x12Z\n" +
	"\x0fCreateShelfItem\x12\".shelves.v1.CreateShelfItemRequest\x1a#.shelves.v1.CreateShelfItemResponseB0Z.proto/shelves_proto/transport/grpc;shelvesgrpcb\x06proto3"

var (
	file_proto_shelves_proto_shelves_proto_rawDescOnce sync.Once
	file_proto_shelves_proto_shelves_proto_rawDescData []byte
)

func file_proto_shelves_proto_shelves_proto_rawDescGZIP() []byte {
	file_proto_shelves_proto_shelves_proto_rawDescOnce.Do(func() {
		file_proto_shelves_proto_shelves_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shelves_proto_shelves_proto_rawDesc), len(file_proto_shelves_proto_shelves_proto_rawDesc)))
	})
	return file_proto_shelves_proto_shelves_proto_rawDescData
}

var file_proto_shelves_proto_shelves_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_shelves_proto_shelves_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_shelves_proto_shelves_proto_goTypes = []any{
	(Shelf)(0),                      // 0: shelves.v1.Shelf
	(*ShelfItem)(nil),               // 1: shelves.v1.ShelfItem
	(*GetShelfItemRequest)(nil),     // 2: shelves.v1.GetShelfItemRequest
	(*GetShelfItemResponse)(nil),    // 3: shelves.v1.GetShelfItemResponse
	(*CreateShelfItemRequest)(nil),  // 4: shelves.v1.CreateShelfItemRequest
	(*CreateShelfItemResponse)(nil), // 5: shelves.v1.CreateShelfItemResponse
}
var file_proto_shelves_proto_shelves_proto_depIdxs = []int32{
	0, // 0: shelves.v1.ShelfItem.shelf:type_name -> shelves.v1.Shelf
	1, // 1: shelves.v1.GetShelfItemResponse.item:type_name -> shelves.v1.ShelfItem
	1, // 2: shelves.v1.CreateShelfItemRequest.item:type_name -> shelves.v1.ShelfItem
	1, // 3: shelves.v1.CreateShelfItemResponse.item:type_name -> shelves.v1.ShelfItem
	2, // 4: shelves.v1.ShelvesService.GetShelfItem:input_type -> shelves.v1.GetShelfItemRequest
	4, // 5: shelves.v1.ShelvesService.CreateShelfItem:input_type -> shelves.v1.CreateShelfItemRequest
	3, // 6: shelves.v1.ShelvesService.GetShelfItem:output_type -> shelves.v1.GetShelfItemResponse
	5, // 7: shelves.v1.ShelvesService.CreateShelfItem:output_type -> shelves.v1.CreateShelfItemResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_shelves_proto_shelves_proto_init() }
func file_proto_shelves_proto_shelves_proto_init() {
	if File_proto_shelves_proto_shelves_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shelves_proto_shelves_proto_rawDesc), len(file_proto_shelves_proto_shelves_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shelves_proto_shelves_proto_goTypes,
		DependencyIndexes: file_proto_shelves_proto_shelves_proto_depIdxs,
		EnumInfos:         file_proto_shelves_proto_shelves_proto_enumTypes,
		MessageInfos:      file_proto_shelves_proto_shelves_proto_msgTypes,
	}.Build()
	File_proto_shelves_proto_shelves_proto = out.File
	file_proto_shelves_proto_shelves_proto_goTypes = nil
	file_proto_shelves_proto_shelves_proto_depIdxs = nil
}
