// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/shelves_proto/shelves.proto

package shelvesgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShelvesService_GetShelfItem_FullMethodName    = "/shelves.v1.ShelvesService/GetShelfItem"
	ShelvesService_CreateShelfItem_FullMethodName = "/shelves.v1.ShelvesService/CreateShelfItem"
)

// ShelvesServiceClient is the client API for ShelvesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShelvesServiceClient interface {
	GetShelfItem(ctx context.Context, in *GetShelfItemRequest, opts ...grpc.CallOption) (*GetShelfItemResponse, error)
	CreateShelfItem(ctx context.Context, in *CreateShelfItemRequest, opts ...grpc.CallOption) (*CreateShelfItemResponse, error)
}

type shelvesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShelvesServiceClient(cc grpc.ClientConnInterface) ShelvesServiceClient {
	return &shelvesServiceClient{cc}
}

func (c *shelvesServiceClient) GetShelfItem(ctx context.Context, in *GetShelfItemRequest, opts ...grpc.CallOption) (*GetShelfItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShelfItemResponse)
	err := c.cc.Invoke(ctx, ShelvesService_GetShelfItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelvesServiceClient) CreateShelfItem(ctx context.Context, in *CreateShelfItemRequest, opts ...grpc.CallOption) (*CreateShelfItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShelfItemResponse)
	err := c.cc.Invoke(ctx, ShelvesService_CreateShelfItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShelvesServiceServer is the server API for ShelvesService service.
// All implementations must embed UnimplementedShelvesServiceServer
// for forward compatibility.
type ShelvesServiceServer interface {
	GetShelfItem(context.Context, *GetShelfItemRequest) (*GetShelfItemResponse, error)
	CreateShelfItem(context.Context, *CreateShelfItemRequest) (*CreateShelfItemResponse, error)
	mustEmbedUnimplementedShelvesServiceServer()
}

// UnimplementedShelvesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShelvesServiceServer struct{}

func (UnimplementedShelvesServiceServer) GetShelfItem(context.Context, *GetShelfItemRequest) (*GetShelfItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShelfItem not implemented")
}
func (UnimplementedShelvesServiceServer) CreateShelfItem(context.Context, *CreateShelfItemRequest) (*CreateShelfItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShelfItem not implemented")
}
func (UnimplementedShelvesServiceServer) mustEmbedUnimplementedShelvesServiceServer() {}
func (UnimplementedShelvesServiceServer) testEmbeddedByValue()                        {}

// UnsafeShelvesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShelvesServiceServer will
// result in compilation errors.
type UnsafeShelvesServiceServer interface {
	mustEmbedUnimplementedShelvesServiceServer()
}

func RegisterShelvesServiceServer(s grpc.ServiceRegistrar, srv ShelvesServiceServer) {
	// If the following call pancis, it indicates UnimplementedShelvesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShelvesService_ServiceDesc, srv)
}

func _ShelvesService_GetShelfItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelfItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelvesServiceServer).GetShelfItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelvesService_GetShelfItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelvesServiceServer).GetShelfItem(ctx, req.(*GetShelfItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelvesService_CreateShelfItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShelfItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelvesServiceServer).CreateShelfItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelvesService_CreateShelfItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelvesServiceServer).CreateShelfItem(ctx, req.(*CreateShelfItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShelvesService_ServiceDesc is the grpc.ServiceDesc for ShelvesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShelvesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shelves.v1.ShelvesService",
	HandlerType: (*ShelvesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShelfItem",
			Handler:    _ShelvesService_GetShelfItem_Handler,
		},
		{
			MethodName: "CreateShelfItem",
			Handler:    _ShelvesService_CreateShelfItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shelves_proto/shelves.proto",
}
