// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/playlist_proto/playlist.proto

package playlistgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_playlist_proto_rawDescGZIP(), []int{0}
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Tracks        []*Song                `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_playlist_proto_rawDescGZIP(), []int{1}
}

func (x *Playlist) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Playlist) GetTracks() []*Song {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetPlaylistForBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistForBookRequest) Reset() {
	*x = GetPlaylistForBookRequest{}
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistForBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistForBookRequest) ProtoMessage() {}

func (x *GetPlaylistForBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistForBookRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistForBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_playlist_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlaylistForBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetPlaylistForBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistForBookResponse) Reset() {
	*x = GetPlaylistForBookResponse{}
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistForBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistForBookResponse) ProtoMessage() {}

func (x *GetPlaylistForBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistForBookResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistForBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_playlist_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlaylistForBookResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type CreatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistRequest) Reset() {
	*x = CreatePlaylistRequest{}
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRequest) ProtoMessage() {}

func (x *CreatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_playlist_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePlaylistRequest) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type CreatePlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistResponse) Reset() {
	*x = CreatePlaylistResponse{}
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistResponse) ProtoMessage() {}

func (x *CreatePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playlist_proto_playlist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_proto_playlist_proto_playlist_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePlaylistResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

var File_proto_playlist_proto_playlist_proto protoreflect.FileDescriptor

const file_proto_playlist_proto_playlist_proto_rawDesc = "" +
	"\n" +
	"#proto/playlist_proto/playlist.proto\x12\vplaylist.v1\"4\n" +
	"\x04Song\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\"N\n" +
	"\bPlaylist\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12)\n" +
	"\x06tracks\x18\x02 \x03(\v2\x11.playlist.v1.SongR\x06tracks\"4\n" +
	"\x19GetPlaylistForBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"O\n" +
	"\x1aGetPlaylistForBookResponse\x121\n" +
	"\bplaylist\x18\x01 \x01(\v2\x15.playlist.v1.PlaylistR\bplaylist\"J\n" +
	"\x15CreatePlaylistRequest\x121\n" +
	"\bplaylist\x18\x01 \x01(\v2\x15.playlist.v1.PlaylistR\bplaylist\"K\n" +
	"\x16CreatePlaylistResponse\x121\n" +
	"\bplaylist\x18\x01 \x01(\v2\x15.playlist.v1.PlaylistR\bplaylist2\xd3\x01\n" +
	"\x0fPlaylistService\x12e\n" +
	"\x12GetPlaylistForBook\x12&.playlist.v1.GetPlaylistForBookRequest\x1a'.playlist.v1.GetPlaylistForBookResponse\x12Y\n" +
	"\x0eCreatePlaylist\x12\".playlist.v1.CreatePlaylistRequest\x1a#.playlist.v1.CreatePlaylistResponseB2Z0proto/playlist_proto/transport/grpc;playlistgrpcb\x06proto3"

var (
	file_proto_playlist_proto_playlist_proto_rawDescOnce sync.Once
	file_proto_playlist_proto_playlist_proto_rawDescData []byte
)

func file_proto_playlist_proto_playlist_proto_rawDescGZIP() []byte {
	file_proto_playlist_proto_playlist_proto_rawDescOnce.Do(func() {
		file_proto_playlist_proto_playlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_playlist_proto_playlist_proto_rawDesc), len(file_proto_playlist_proto_playlist_proto_rawDesc)))
	})
	return file_proto_playlist_proto_playlist_proto_rawDescData
}

var file_proto_playlist_proto_playlist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_playlist_proto_playlist_proto_goTypes = []any{
	(*Song)(nil),                       // 0: playlist.v1.Song
	(*Playlist)(nil),                   // 1: playlist.v1.Playlist
	(*GetPlaylistForBookRequest)(nil),  // 2: playlist.v1.GetPlaylistForBookRequest
	(*GetPlaylistForBookResponse)(nil), // 3: playlist.v1.GetPlaylistForBookResponse
	(*CreatePlaylistRequest)(nil),      // 4: playlist.v1.CreatePlaylistRequest
	(*CreatePlaylistResponse)(nil),     // 5: playlist.v1.CreatePlaylistResponse
}
var file_proto_playlist_proto_playlist_proto_depIdxs = []int32{
	0, // 0: playlist.v1.Playlist.tracks:type_name -> playlist.v1.Song
	1, // 1: playlist.v1.GetPlaylistForBookResponse.playlist:type_name -> playlist.v1.Playlist
	1, // 2: playlist.v1.CreatePlaylistRequest.playlist:type_name -> playlist.v1.Playlist
	1, // 3: playlist.v1.CreatePlaylistResponse.playlist:type_name -> playlist.v1.Playlist
	2, // 4: playlist.v1.PlaylistService.GetPlaylistForBook:input_type -> playlist.v1.GetPlaylistForBookRequest
	4, // 5: playlist.v1.PlaylistService.CreatePlaylist:input_type -> playlist.v1.CreatePlaylistRequest
	3, // 6: playlist.v1.PlaylistService.GetPlaylistForBook:output_type -> playlist.v1.GetPlaylistForBookResponse
	5, // 7: playlist.v1.PlaylistService.CreatePlaylist:output_type -> playlist.v1.CreatePlaylistResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_playlist_proto_playlist_proto_init() }
func file_proto_playlist_proto_playlist_proto_init() {
	if File_proto_playlist_proto_playlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_playlist_proto_playlist_proto_rawDesc), len(file_proto_playlist_proto_playlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_playlist_proto_playlist_proto_goTypes,
		DependencyIndexes: file_proto_playlist_proto_playlist_proto_depIdxs,
		MessageInfos:      file_proto_playlist_proto_playlist_proto_msgTypes,
	}.Build()
	File_proto_playlist_proto_playlist_proto = out.File
	file_proto_playlist_proto_playlist_proto_goTypes = nil
	file_proto_playlist_proto_playlist_proto_depIdxs = nil
}
