// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/library.proto

package librarygrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Edition       string                 `protobuf:"bytes,5,opt,name=edition,proto3" json:"edition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_proto_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_proto_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Book) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_proto_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_proto_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_proto_library_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_library_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_proto_library_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_library_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

var File_proto_library_proto protoreflect.FileDescriptor

const file_proto_library_proto_rawDesc = "" +
	"\n" +
	"\x13proto/library.proto\x12\n" +
	"library.v1\"t\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\x12\x18\n" +
	"\aedition\x18\x05 \x01(\tR\aedition\" \n" +
	"\x0eGetBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0fGetBookResponse\x12$\n" +
	"\x04book\x18\x01 \x01(\v2\x10.library.v1.BookR\x04book\"9\n" +
	"\x11CreateBookRequest\x12$\n" +
	"\x04book\x18\x01 \x01(\v2\x10.library.v1.BookR\x04book\":\n" +
	"\x12CreateBookResponse\x12$\n" +
	"\x04book\x18\x01 \x01(\v2\x10.library.v1.BookR\x04book2\xa1\x01\n" +
	"\x0eLibraryService\x12B\n" +
	"\aGetBook\x12\x1a.library.v1.GetBookRequest\x1a\x1b.library.v1.GetBookResponse\x12K\n" +
	"\n" +
	"CreateBook\x12\x1d.library.v1.CreateBookRequest\x1a\x1e.library.v1.CreateBookResponseB#Z!proto//transport/grpc;librarygrpcb\x06proto3"

var (
	file_proto_library_proto_rawDescOnce sync.Once
	file_proto_library_proto_rawDescData []byte
)

func file_proto_library_proto_rawDescGZIP() []byte {
	file_proto_library_proto_rawDescOnce.Do(func() {
		file_proto_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_library_proto_rawDesc), len(file_proto_library_proto_rawDesc)))
	})
	return file_proto_library_proto_rawDescData
}

var file_proto_library_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_library_proto_goTypes = []any{
	(*Book)(nil),               // 0: library.v1.Book
	(*GetBookRequest)(nil),     // 1: library.v1.GetBookRequest
	(*GetBookResponse)(nil),    // 2: library.v1.GetBookResponse
	(*CreateBookRequest)(nil),  // 3: library.v1.CreateBookRequest
	(*CreateBookResponse)(nil), // 4: library.v1.CreateBookResponse
}
var file_proto_library_proto_depIdxs = []int32{
	0, // 0: library.v1.GetBookResponse.book:type_name -> library.v1.Book
	0, // 1: library.v1.CreateBookRequest.book:type_name -> library.v1.Book
	0, // 2: library.v1.CreateBookResponse.book:type_name -> library.v1.Book
	1, // 3: library.v1.LibraryService.GetBook:input_type -> library.v1.GetBookRequest
	3, // 4: library.v1.LibraryService.CreateBook:input_type -> library.v1.CreateBookRequest
	2, // 5: library.v1.LibraryService.GetBook:output_type -> library.v1.GetBookResponse
	4, // 6: library.v1.LibraryService.CreateBook:output_type -> library.v1.CreateBookResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_library_proto_init() }
func file_proto_library_proto_init() {
	if File_proto_library_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_library_proto_rawDesc), len(file_proto_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_library_proto_goTypes,
		DependencyIndexes: file_proto_library_proto_depIdxs,
		MessageInfos:      file_proto_library_proto_msgTypes,
	}.Build()
	File_proto_library_proto = out.File
	file_proto_library_proto_goTypes = nil
	file_proto_library_proto_depIdxs = nil
}
