// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/reviews_proto/reviews.proto

package reviewsgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_reviews_proto_reviews_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Review) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reviews_proto_reviews_proto_rawDescGZIP(), []int{1}
}

func (x *GetReviewsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsResponse) Reset() {
	*x = GetReviewsResponse{}
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsResponse) ProtoMessage() {}

func (x *GetReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reviews_proto_reviews_proto_rawDescGZIP(), []int{2}
}

func (x *GetReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_reviews_proto_reviews_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviews_proto_reviews_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_reviews_proto_reviews_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

var File_proto_reviews_proto_reviews_proto protoreflect.FileDescriptor

const file_proto_reviews_proto_reviews_proto_rawDesc = "" +
	"\n" +
	"!proto/reviews_proto/reviews.proto\x12\n" +
	"reviews.v1\"v\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\",\n" +
	"\x11GetReviewsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"B\n" +
	"\x12GetReviewsResponse\x12,\n" +
	"\areviews\x18\x01 \x03(\v2\x12.reviews.v1.ReviewR\areviews\"A\n" +
	"\x13CreateReviewRequest\x12*\n" +
	"\x06review\x18\x01 \x01(\v2\x12.reviews.v1.ReviewR\x06review\"B\n" +
	"\x14CreateReviewResponse\x12*\n" +
	"\x06review\x18\x01 \x01(\v2\x12.reviews.v1.ReviewR\x06review2\xaf\x01\n" +
	"\rReviewService\x12K\n" +
	"\n" +
	"GetReviews\x12\x1d.reviews.v1.GetReviewsRequest\x1a\x1e.reviews.v1.GetReviewsResponse\x12Q\n" +
	"\fCreateReview\x12\x1f.reviews.v1.CreateReviewRequest\x1a .reviews.v1.CreateReviewResponseB0Z.proto/reviews_proto/transport/grpc;reviewsgrpcb\x06proto3"

var (
	file_proto_reviews_proto_reviews_proto_rawDescOnce sync.Once
	file_proto_reviews_proto_reviews_proto_rawDescData []byte
)

func file_proto_reviews_proto_reviews_proto_rawDescGZIP() []byte {
	file_proto_reviews_proto_reviews_proto_rawDescOnce.Do(func() {
		file_proto_reviews_proto_reviews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reviews_proto_reviews_proto_rawDesc), len(file_proto_reviews_proto_reviews_proto_rawDesc)))
	})
	return file_proto_reviews_proto_reviews_proto_rawDescData
}

var file_proto_reviews_proto_reviews_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_reviews_proto_reviews_proto_goTypes = []any{
	(*Review)(nil),               // 0: reviews.v1.Review
	(*GetReviewsRequest)(nil),    // 1: reviews.v1.GetReviewsRequest
	(*GetReviewsResponse)(nil),   // 2: reviews.v1.GetReviewsResponse
	(*CreateReviewRequest)(nil),  // 3: reviews.v1.CreateReviewRequest
	(*CreateReviewResponse)(nil), // 4: reviews.v1.CreateReviewResponse
}
var file_proto_reviews_proto_reviews_proto_depIdxs = []int32{
	0, // 0: reviews.v1.GetReviewsResponse.reviews:type_name -> reviews.v1.Review
	0, // 1: reviews.v1.CreateReviewRequest.review:type_name -> reviews.v1.Review
	0, // 2: reviews.v1.CreateReviewResponse.review:type_name -> reviews.v1.Review
	1, // 3: reviews.v1.ReviewService.GetReviews:input_type -> reviews.v1.GetReviewsRequest
	3, // 4: reviews.v1.ReviewService.CreateReview:input_type -> reviews.v1.CreateReviewRequest
	2, // 5: reviews.v1.ReviewService.GetReviews:output_type -> reviews.v1.GetReviewsResponse
	4, // 6: reviews.v1.ReviewService.CreateReview:output_type -> reviews.v1.CreateReviewResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_reviews_proto_reviews_proto_init() }
func file_proto_reviews_proto_reviews_proto_init() {
	if File_proto_reviews_proto_reviews_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reviews_proto_reviews_proto_rawDesc), len(file_proto_reviews_proto_reviews_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reviews_proto_reviews_proto_goTypes,
		DependencyIndexes: file_proto_reviews_proto_reviews_proto_depIdxs,
		MessageInfos:      file_proto_reviews_proto_reviews_proto_msgTypes,
	}.Build()
	File_proto_reviews_proto_reviews_proto = out.File
	file_proto_reviews_proto_reviews_proto_goTypes = nil
	file_proto_reviews_proto_reviews_proto_depIdxs = nil
}
