// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/gateway_proto/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // opcional, solo si se quiere traer la shelf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookOverviewRequest) Reset() {
	*x = GetBookOverviewRequest{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookOverviewRequest) ProtoMessage() {}

func (x *GetBookOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetBookOverviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookOverviewRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *GetBookOverviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OverviewBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Edition       string                 `protobuf:"bytes,5,opt,name=edition,proto3" json:"edition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewBook) Reset() {
	*x = OverviewBook{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewBook) ProtoMessage() {}

func (x *OverviewBook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewBook.ProtoReflect.Descriptor instead.
func (*OverviewBook) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *OverviewBook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OverviewBook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OverviewBook) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *OverviewBook) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *OverviewBook) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Review) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Tracks        []*Song                `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Playlist) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Playlist) GetTracks() []*Song {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type ShelfItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Shelf         string                 `protobuf:"bytes,3,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShelfItem) Reset() {
	*x = ShelfItem{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShelfItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShelfItem) ProtoMessage() {}

func (x *ShelfItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShelfItem.ProtoReflect.Descriptor instead.
func (*ShelfItem) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ShelfItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShelfItem) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *ShelfItem) GetShelf() string {
	if x != nil {
		return x.Shelf
	}
	return ""
}

type GetBookOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *OverviewBook          `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Reviews       []*Review              `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Playlist      *Playlist              `protobuf:"bytes,3,opt,name=playlist,proto3" json:"playlist,omitempty"`
	Shelf         *ShelfItem             `protobuf:"bytes,4,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookOverviewResponse) Reset() {
	*x = GetBookOverviewResponse{}
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookOverviewResponse) ProtoMessage() {}

func (x *GetBookOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetBookOverviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetBookOverviewResponse) GetBook() *OverviewBook {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *GetBookOverviewResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *GetBookOverviewResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

func (x *GetBookOverviewResponse) GetShelf() *ShelfItem {
	if x != nil {
		return x.Shelf
	}
	return nil
}

var File_proto_gateway_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"!proto/gateway_proto/gateway.proto\x12\n" +
	"gateway.v1\"J\n" +
	"\x16GetBookOverviewRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"|\n" +
	"\fOverviewBook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\x12\x18\n" +
	"\aedition\x18\x05 \x01(\tR\aedition\"v\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"4\n" +
	"\x04Song\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\"M\n" +
	"\bPlaylist\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12(\n" +
	"\x06tracks\x18\x02 \x03(\v2\x10.gateway.v1.SongR\x06tracks\"S\n" +
	"\tShelfItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05shelf\x18\x03 \x01(\tR\x05shelf\"\xd4\x01\n" +
	"\x17GetBookOverviewResponse\x12,\n" +
	"\x04book\x18\x01 \x01(\v2\x18.gateway.v1.OverviewBookR\x04book\x12,\n" +
	"\areviews\x18\x02 \x03(\v2\x12.gateway.v1.ReviewR\areviews\x120\n" +
	"\bplaylist\x18\x03 \x01(\v2\x14.gateway.v1.PlaylistR\bplaylist\x12+\n" +
	"\x05shelf\x18\x04 \x01(\v2\x15.gateway.v1.ShelfItemR\x05shelf2l\n" +
	"\x0eGatewayService\x12Z\n" +
	"\x0fGetBookOverview\x12\".gateway.v1.GetBookOverviewRequest\x1a#.gateway.v1.GetBookOverviewResponseB\x1fZ\x1dproto/gateway_proto;gatewaypbb\x06proto3"

var (
	file_proto_gateway_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_gateway_proto_gateway_proto_goTypes = []any{
	(*GetBookOverviewRequest)(nil),  // 0: gateway.v1.GetBookOverviewRequest
	(*OverviewBook)(nil),            // 1: gateway.v1.OverviewBook
	(*Review)(nil),                  // 2: gateway.v1.Review
	(*Song)(nil),                    // 3: gateway.v1.Song
	(*Playlist)(nil),                // 4: gateway.v1.Playlist
	(*ShelfItem)(nil),               // 5: gateway.v1.ShelfItem
	(*GetBookOverviewResponse)(nil), // 6: gateway.v1.GetBookOverviewResponse
}
var file_proto_gateway_proto_gateway_proto_depIdxs = []int32{
	3, // 0: gateway.v1.Playlist.tracks:type_name -> gateway.v1.Song
	1, // 1: gateway.v1.GetBookOverviewResponse.book:type_name -> gateway.v1.OverviewBook
	2, // 2: gateway.v1.GetBookOverviewResponse.reviews:type_name -> gateway.v1.Review
	4, // 3: gateway.v1.GetBookOverviewResponse.playlist:type_name -> gateway.v1.Playlist
	5, // 4: gateway.v1.GetBookOverviewResponse.shelf:type_name -> gateway.v1.ShelfItem
	0, // 5: gateway.v1.GatewayService.GetBookOverview:input_type -> gateway.v1.GetBookOverviewRequest
	6, // 6: gateway.v1.GatewayService.GetBookOverview:output_type -> gateway.v1.GetBookOverviewResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_gateway_proto_init() }
func file_proto_gateway_proto_gateway_proto_init() {
	if File_proto_gateway_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto_gateway_proto = out.File
	file_proto_gateway_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_gateway_proto_depIdxs = nil
}
